import { type NextPage } from "next";
import Head from "next/head";
import { signIn, useSession } from "next-auth/react";

const Home: NextPage = () => {
  const { data: session } = useSession();

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <button className="border-2 p-1" onClick={() => void signIn()}>Sign In</button>
        <hr />
        <p>{JSON.stringify(session)}</p>
      </main>
    </>
  );
};

export default Home;
